command error check

diff --git a/src/dk_build b/src/dk_build
--- a/src/dk_build
+++ b/src/dk_build
@@ -17,6 +17,14 @@ DOCKER_ISO="$2"
 DOCKER_IMAGE=`echo $DOCKER_ISO | awk -F. '{print $1}'`
 TAR_IMAGE_NAME="${DOCKER_IMAGE}.tar"
 
+DISO_SET=`echo $DOCKER_ISO | awk -F. '{print $2}'`
+
+if [ -z $DISO_SET ]; then
+    echo "[ error ] specify docker image name with (.diso) extension" 
+    exit 1
+fi
+
+
 if [ ! -f "$DOCKER_FILE" ]; then
     echo "[ error ] Dockerfile Missing ( $DOCKER_FILE )"
     exit 1
@@ -26,7 +34,21 @@ fi
 docker image rm  $DOCKER_IMAGE
 echo "[ status ] Building Custom Docker Image from ( $DOCKER_FILE )"
 docker build - < $DOCKER_FILE  -t $DOCKER_IMAGE
+
+if [ $? -ne 0 ]; then
+    echo "[ error ] docker build failed"
+    exit 1
+fi
+
+
 docker save -o $TAR_IMAGE_NAME $DOCKER_IMAGE
+
+if [ $? -ne 0 ]; then
+    echo "[ error ] docker save failed"
+    exit 1
+fi
+
+
 docker image rm  $DOCKER_IMAGE
 mv $TAR_IMAGE_NAME $DOCKER_ISO
 
diff --git a/src/dk_container_create b/src/dk_container_create
--- a/src/dk_container_create
+++ b/src/dk_container_create
@@ -16,6 +16,22 @@ CONTAINER_NAME="$2"
 IMAGE_NAME=`echo $DOCKER_ISO_NAME | awk -F. '{print $1}'`
 TAR_IMAGE_NAME="${IMAGE_NAME}.tar"
 
+DISO_SET=`echo $DOCKER_ISO_NAME | awk -F. '{print $2}'`
+
+if [ -z $DISO_SET ]; then
+    echo "[ error ] specify docker image name with (.diso) extension" 
+    exit 1
+fi
+
+
+
+if [ -z $DISO_SET ]; then
+    echo "[ error ] specify docker image name with (.diso) extension" 
+    exit 1
+fi
+
+
+
 if [ ! -f "$DOCKER_ISO_NAME" ]; then
     echo "[ error ] Docker ISO Image File Missing ( $DOCKER_ISO_NAME )"
     exit 1
@@ -45,18 +61,21 @@ docker image rm  $IMAGE_NAME &> /dev/null
 echo "[ status ] Load Docker Image ( $DOCKER_ISO_NAME  ) ( $TAR_IMAGE_NAME )"
 docker load -i $TAR_IMAGE_NAME
 
+if [ $? -ne 0 ]; then
+    echo "[ error ] Docker Load"
+    exit 1
+fi
+
 echo
 docker create -t -i -v ~/docker_share:/home/share --name $CONTAINER_NAME $IMAGE_NAME bash
 
-
-if [ $? -eq 0 ]; then
-    echo "[ success ] docker container created successfully ( container_name = $CONTAINER_NAME )"
-    rm -rf $TAR_IMAGE_NAME
-    exit 0
-else
+if [ $? -ne 0 ]; then
     echo "[ error ] unable to create docker container ( container_name = $CONTAINER_NAME )"
     rm -rf $TAR_IMAGE_NAME
     exit 1
 fi
+
+echo "[ success ] docker container created successfully ( container_name = $CONTAINER_NAME )"
+rm -rf $TAR_IMAGE_NAME
 
 
diff --git a/src/dk_container_export b/src/dk_container_export
--- a/src/dk_container_export
+++ b/src/dk_container_export
@@ -16,19 +16,34 @@ CONTAINER_NAME="$1"
 DOCKER_OVA_FILE_NAME="$2"
 TAR_IMAGE_NAME="${DOCKER_OVA_FILE_NAME}.tar"
 
+DOVA_SET=`echo $DOCKER_OVA_FILE_NAME | awk -F. '{print $2}'`
+
+if [ -z $DOVA_SET ]; then
+    echo "[ error ] specify docker appliance name with (.dova) extension" 
+    exit 1
+fi
+
+
+
 rm -rf $TAR_IMAGE_NAME
 
 docker export $CONTAINER_NAME > $TAR_IMAGE_NAME
+
+if [ $? -ne 0 ]; then
+    echo "[ error ] docker export"
+	echo
+    exit 1
+fi
+
+
 mv $TAR_IMAGE_NAME $DOCKER_OVA_FILE_NAME
 
-if [ $? -eq 0 ]; then
-    echo "[ success ] docker container exported successfully ( Output File : $DOCKER_OVA_FILE_NAME )"
-	echo
-    exit 0
-else
+if [ $? -ne 0 ]; then
     echo "[ error ] unable to export container ( container_name = $CONTAINER_NAME )"
 	echo
     exit 1
 fi
 
 
+echo "[ success ] docker container exported successfully ( Output File : $DOCKER_OVA_FILE_NAME )"
+echo
diff --git a/src/dk_container_import b/src/dk_container_import
--- a/src/dk_container_import
+++ b/src/dk_container_import
@@ -18,6 +18,14 @@ IMAGE_NAME="image_${CONTAINER_NAME}"
 APPLIANCE_PREFIX=`echo $APPLIANCE_NAME | awk -F. '{print $1}'`
 APPLIANCE_TAR="${APPLIANCE_PREFIX}.tar"
 
+DOVA_SET=`echo $APPLIANCE_NAME | awk -F. '{print $2}'`
+
+if [ -z $DOVA_SET ]; then
+    echo "[ error ] specify docker appliance name with (.dova) extension" 
+    exit 1
+fi
+
+
 
 if [ ! -f "$APPLIANCE_NAME" ]; then
     echo "[ error ] Docker Container Appliance Missing ($APPLIANCE_NAME)"
