ut

diff --git a/src/dk_build b/src/dk_build
--- a/src/dk_build
+++ b/src/dk_build
@@ -12,15 +12,24 @@ if [ -z $2 ]; then
 fi
 
 DOCKER_FILE="$1"
-DOCKER_IMAGE="$2"
-DOCKER_IMAGE_FILE="${DOCKER_IMAGE}"
+DOCKER_ISO="$2"
+
+DOCKER_IMAGE=`echo $DOCKER_ISO | awk -F. '{print $1}'`
+TAR_IMAGE_NAME="${DOCKER_IMAGE}.tar"
+
+if [ ! -f "$DOCKER_FILE" ]; then
+    echo "[ error ] Dockerfile Missing ( $DOCKER_FILE )"
+    exit 1
+fi
+
 
 docker image rm  $DOCKER_IMAGE
 echo "[ status ] Building Custom Docker Image from ( $DOCKER_FILE )"
 docker build - < $DOCKER_FILE  -t $DOCKER_IMAGE
-docker save -o $DOCKER_IMAGE_FILE $DOCKER_IMAGE
+docker save -o $TAR_IMAGE_NAME $DOCKER_IMAGE
 docker image rm  $DOCKER_IMAGE
+mv $TAR_IMAGE_NAME $DOCKER_ISO
 
-echo "[ status ] New docker image is created by name ( $DOCKER_IMAGE_FILE )"
+echo "[ status ] New docker image is created by name ( $DOCKER_ISO )"
 
 echo
